#!/usr/bin/env python

# hvac_usage - report HVAC usage
#
# Usage: hvac_usage [config]
#
#
# Copyright (c) 2012, James Ryan Cresawn
# All rights reserved.

import httplib
import json
import sys

if len(sys.argv) > 2:
    sys.exit('Usage: %s [config]' % sys.argv[0])
elif len(sys.argv) > 1:
    if sys.argv[1] == "config":
        print "graph_args --base 1000 --lower-limit 0 --upper-limit 100"
	print "graph_scale no"
        print "graph_category thermostat"
        print "graph_title HVAC usage"
        print "graph_vlabel %"
        print "cool_usage.label cool"
        print "cool_usage.colour 0000ff"
        print "cool_usage.draw AREA"
        print "cool_usage.min 0"
        print "cool_usage.cdef cool_usage,14.40,/"
        print "heat_usage.label heat"
        print "heat_usage.colour ff0000"
        print "heat_usage.type COUNTER"
        print "heat_usage.draw AREA"
        print "heat_usage.min 0"
        print "heat_usage.cdef heat_usage,14.40,/"
        sys.exit(0)
    else:
        sys.exit('Usage: %s [config]' % sys.argv[0])

conn = httplib.HTTPConnection("192.168.10.15")
conn.request("GET", "/tstat/datalog")
r = conn.getresponse()
if r.status == 200:
    data = r.read()
    conn.close()
    d = json.loads(data)
    cool_hour = d['today']['cool_runtime']['hour']
    cool_minute = d['today']['cool_runtime']['minute']
    print "cool_usage.value", cool_hour * 60 + cool_minute
    heat_hour = d['today']['heat_runtime']['hour']
    heat_minute = d['today']['heat_runtime']['minute']
    print "heat_usage.value", heat_hour * 60 + heat_minute
else:
    sys.exit(1)
