#!/usr/bin/env python

# temperature - report temperature from thermostat
#
# Usage: temperature [config]
#
#
# Copyright (c) 2012, James Ryan Cresawn
# All rights reserved.

import httplib
import json
import sys

zip = "85719"

if len(sys.argv) > 2:
    sys.exit('Usage: %s [config]' % sys.argv[0])
elif len(sys.argv) > 1:
    if sys.argv[1] == "config":
        print "graph_scale yes"
        print "graph_category thermostat"
        print "graph_title Temperature"
        print "graph_vlabel degrees (F)"
        print "indoor.label indoor"
        print "outdoor.label ZIP Code: " + zip
        sys.exit(0)
    else:
        sys.exit('Usage: %s [config]' % sys.argv[0])

def getIndoorTemp():
    conn = httplib.HTTPConnection("192.168.10.15")
    conn.request("GET", "/tstat/temp")
    r = conn.getresponse()
    if r.status == 200:
        data = r.read()
        conn.close()
        d = json.loads(data)
        return d['temp']
    else:
        sys.exit(1)

def getOutdoorTemp(zip):
    conn = httplib.HTTPConnection("query.yahooapis.com")
    url_end = "/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20location%3D%22" + zip + "%22&format=json"
    conn.request("GET", url_end)
    r = conn.getresponse()
    if r.status == 200:
        data = r.read()
        conn.close()
        d = json.loads(data)
        return d['query']['results']['channel']['item']['condition']['temp']
    else:
        sys.exit(1)

print "indoor.value", getIndoorTemp()
print "outdoor.value", getOutdoorTemp(zip)
